name: 'Push to Redocly'

on:
  push:
    branches:
      - '**'

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      statuses: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: 'Push files and wait for deployment'
        uses: redocly/reunite-push-action@v1
        with:
          organization: 'surviving-monkey'
          project: 'mad-mango'
          mountPath: '/cicd'
          files: '/'
          domain: 'https://app.lab3.blueharvest.cloud'
        env:
          REDOCLY_AUTHORIZATION: ${{ secrets.REDOCLY_AUTHORIZATION }}